### ISSUE TITLE
Crash FocusState with two TextFields

### ISSUE THREAD

**Issue by fpcornelis** [shaps80/SwiftUIBackports#61] opened 2023-08-11 14:43 UTC
If you use focus state with two Textfields, app crashes.

If you replace VStack with Form/List it works, but I dont want use a Form.

```
import SwiftUI
import SwiftUIBackports

struct FocusState: View {
    var body: some View {
        NavigationLink {
            Demo()
                .backport.navigationTitle("Sign In")
        } label: {
            Text("Focus State")
        }
    }
}

private struct Demo: View {
    enum Field: Hashable {
        case username
        case password
    }
    
    @State private var username = ""
    @State private var password = ""
    @Backport.FocusState private var focusedField: Field?
    
    var body: some View {
        VStack {
            TextField("Username", text: $username)
                .backport.focused($focusedField, equals: .username)
                .backport.submitLabel(.next)
                .backport.onSubmit {
                    if !username.isEmpty {
                        focusedField = .password
                    }
                }
            
            
            TextField("Password", text: $password)
                .backport.focused($focusedField, equals: .password)
                .backport.submitLabel(.done)
                .backport.onSubmit {
                    signIn()
                }
            
            
            Button("Sign In") {
                signIn()
                
            }
        }
        .padding()
        
        .onAppear {
            focusedField = .username
        }
    }
    
    private func signIn() {
        if username.isEmpty {
            focusedField = .username
        } else if password.isEmpty {
            focusedField = .password
        } else {
            focusedField = nil
            print(username, password)
        }
    }
}
```

**Comment by elbelga** [comment] 2023-08-31 09:33
Stacktrace

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	       0x105b1ee3c bool objc::DenseMapBase<objc::DenseMap<DisguisedPtr<objc_object const>, unsigned long, (anonymous namespace)::RefcountMapValuePurgeable, objc::DenseMapInfo<DisguisedPtr<objc_object const>>, objc::detail::DenseMapPair<DisguisedPtr<objc_object const>, unsigned long>>, DisguisedPtr<objc_object const>, unsigned long, (anonymous namespace)::RefcountMapValuePurgeable, objc::DenseMapInfo<DisguisedPtr<objc_object const>>, objc::detail::DenseMapPair<DisguisedPtr<objc_object const>, unsigned long>>::LookupBucketFor<DisguisedPtr<objc_object const>>(DisguisedPtr<objc_object const> const&, objc::detail::DenseMapPair<DisguisedPtr<objc_object const>, unsigned long>*&) + 4
1   libobjc.A.dylib               	       0x105b1f9c7 objc::DenseMapBase<objc::DenseMap<DisguisedPtr<objc_object const>, unsigned long, (anonymous namespace)::RefcountMapValuePurgeable, objc::DenseMapInfo<DisguisedPtr<objc_object const>>, objc::detail::DenseMapPair<DisguisedPtr<objc_object const>, unsigned long>>, DisguisedPtr<objc_object const>, unsigned long, (anonymous namespace)::RefcountMapValuePurgeable, objc::DenseMapInfo<DisguisedPtr<objc_object const>>, objc::detail::DenseMapPair<DisguisedPtr<objc_object const>, unsigned long>>::operator[](DisguisedPtr<objc_object const>&&) + 35
2   libobjc.A.dylib               	       0x105b1f97d objc_object::sidetable_retain(bool) + 89
3   BackportsDemo                 	       0x10500b164 Coordinator.responds(to:) + 84
4   BackportsDemo                 	       0x10500b2c7 @objc Coordinator.responds(to:) + 39
5   BackportsDemo                 	       0x10500b221 Coordinator.responds(to:) + 273
6   BackportsDemo                 	       0x10500b2c7 @objc Coordinator.responds(to:) + 39
7   BackportsDemo                 	       0x10500b221 Coordinator.responds(to:) + 273
8   BackportsDemo                 	       0x10500b2c7 @objc Coordinator.responds(to:) + 39
9   BackportsDemo                 	       0x10500b221 Coordinator.responds(to:) + 273
10  BackportsDemo                 	       0x10500b2c7 @objc Coordinator.responds(to:) + 39
11  BackportsDemo                 	       0x10500b221 Coordinator.responds(to:) + 273
12  BackportsDemo                 	       0x10500b2c7 @objc Coordinator.responds(to:) + 39
13  BackportsDemo                 	       0x10500b221 Coordinator.responds(to:) + 273
....


[SwiftUIBackportsDemo-main.zip](https://github.com/shaps80/SwiftUIBackports/files/12484722/SwiftUIBackportsDemo-main.zip)

**Comment by shaps80** [comment] 2023-09-01 09:01
Interesting, I think this indicates an underlying issue (similar to #62) because they have almost identical configurations for the delegate-dance in order to prevent introducing issues into native SwiftUI code, as well as allow multiple modifiers to co-exist.

@roland-schmitz-ocu worth you taking a look at this as well, I think its related and perhaps even proves my points I made on the other issue.

I'm fairly confident this all worked previously, so I wonder if something was introduced since iOS 16 that just wasn't uncovered until now since a lot of users of this library are here for "backports" therefore not iOS the latest iOS versions.

**Comment by roland-schmitz-ocu** [comment] 2023-09-09 14:55
Thanks @shaps80 for the pointer to this issue. I could reproduce it issue on iOS 15, 16 and 17 and yes you are right, the issue is very similar to #62. Also here the delegate dance happened multiple times which created a cycle in the delegate chain. I could fix it in the same way as in the other two cases by not touching the delegate when it is already been setup. I added a third commit to my PR #63 which 100% fixes also this issue on iOS 15, iOS 16 and iOS 17.

**Comment by shaps80** [comment] 2023-09-15 21:36
> Thanks @shaps80 for the pointer to this issue. I could reproduce it on iOS 15, 16 and 17 and yes you are right, the issue is very similar to #62. Also here the delegate dance happened multiple times which created a cycle in the delegate chain. I could fix it in the same way as in the other two cases by not touching the delegate when it has already been setup. I added a third commit to my PR #63 which 100% fixes also this issue on iOS 15, iOS 16 and iOS 17.

Perfect, I merged already :)

**Closed by shaps80** 2023-09-15 21:36 UTC
Labels: bug
